on:
  issue_comment:
    types: [created]
name: Pull Requests Comment
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: PullRequestHandler
        uses: Ash258/Scoop-GithubActions@stable
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITH_EMAIL: 18361388+MaoKwen@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  